# Database config
spring.datasource.url=jdbc:postgresql://localhost:5433/my-db
spring.datasource.username=user
spring.datasource.password=user
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

frontend.url=http:localhost:5173

email.username=mikos@gmail.com
email.password=dupa123

# Logging
logging.level.root=WARN
# logging.level.org.hibernate.SQL=DEBUG
spring.main.banner-mode=off

# Server config
server.servlet.context-path=/api

# S3 config
cloud.do.endpoint=test
cloud.do.credentials.accessKey=test
cloud.do.credentials.secretKey=test
cloud.do.region.name=test
cloud.do.bucket.name=test
cloud.do.cdn.endpoint=test

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB