name: Backend deployment

on:
  push:
    branches: [ main ]
    paths:
      - backend/**
      - .github/workflows/backend-*.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  build:
    env:
      AWS_REGION: eu-central-1
      ECR_REPOSITORY: code-mastery
    permissions:
      checks: write
      contents: read
      id-token: write
      issues: read
      pull-requests: write
    runs-on: ubuntu-latest
    name: Build backend
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup JDK
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c #v6.0.0
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - name: Build and test
        run: mvn --batch-mode verify
      - name: Store results
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #v7.0.1
        with:
          name: Tests results
          path: target/surefire-reports
      - name: Build docker image
        run: docker build -f backend/Dockerfile -t "${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}" backend
      - name: 🔧 Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@517a711dbcd0e402f90c77e7e2f81e849156e31d # v6.2.2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
      - name: ☁️ Login to Amazon ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@d539f0932e70871a027e9d5a9d8fc38589180a64 # v2.1.6
      - name: 📦 Push docker image
        env:
          ECR_REGISTRY: ${{ steps.ecr.outputs.registry }}
        run: |
          docker tag "code-mastery:${{ github.sha }}" "$ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}"
          docker push "$ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}"